FROM ubuntu:22.04

RUN apt update
RUN apt install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt install -y nodejs

WORKDIR /usr/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install
COPY ./ ./

EXPOSE 3000
EXPOSE 5173

CMD ["npm", "run", "dev", "--host", "0.0.0.0"]
