services:
  db:
    image: postgres:13.7
    container_name: rocketprint-db
    env_file:
      - ./.envs/.env.dev
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    container_name: rocketprint-nginx
    ports:
      - "80:80"
    depends_on:
      - db
      - app

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: rocketprint-app
    env_file:
      - ./.envs/.env.dev
    volumes:
      - ./app/src:/app/src
    entrypoint: |
      npm run dev
